### ISSUE TITLE
Game setup: lay out grid of different types of tiles in text file using tile names separated by tabs

### ISSUE THREAD

**Issue by phillipgray** [code-newbies/python-thursday-adventure#10]

**Comment by jcode89** [comment]
For this issue and issue #11 perhaps we make a class Room(): that will handle creating the room tiles and what not? Instead of pulling data from a file?

**Comment by rubyyot** [comment]
This sounds like a good way forward.  I like the Room class idea.  There may be a need for configuration files at some point, but I agree with @jcode89 that a Room class makes sense.

**Comment by jcode89** [comment]
Would other files like YAML or JSON or even CSV be easier to pull and store data, than a text file? Also, @rubyyot mentioned the use of YAML or JSON.

**Comment by rubyyot** [comment]
json is simple to serialize with the picklejson module.

**Comment by rubyyot** [comment]
sorry jsonpickle. http://www.theregister.co.uk/2015/06/17/apple_hosed_boffins_drop_0day_mac_ios_research_blitzkrieg/?mt=1434638890470

**Comment by rubyyot** [comment]
argh.  this is the right link.  https://pypi.python.org/pypi/jsonpickle

**Comment by jcode89** [comment]
Oh I've never heard of jsonpickle, it looks promising.

**Comment by jcode89** [comment]
Just an update. I tried using a .csv file first, ran it through some very basic code to pull data and create a dictionary. So far so good :+1:

**Comment by rubyyot** [comment]
cool!

**Comment by jcode89** [comment]
Created branch and pushed the file to it. My apologies for forgetting to put Issue-10 on the end.

**Comment by rubyyot** [comment]
@jcode89 We will let it slide :)

**Comment by jcode89** [comment]
😁 Yay! 

Jonathan Colón
