### ISSUE TITLE
Upon entering a new room, there is a description of the space.

### ISSUE THREAD

**Issue by phillipgray** [code-newbies/python-thursday-adventure#12]

**Comment by rubyyot** [comment]
I think that this should read "Upon entering any room, a description of the space is given to the player"

**Comment by jcode89** [comment]
I think we should add description to the JSON files that gives a description of the room. Then we can just pull it out of the file when player == entrance location, or something.

**Comment by jamalhansen** [comment]
that makes sense, i agree

**Comment by jcode89** [comment]
:) Awesome!
