### ISSUE TITLE
Upon entering any tile, the available movements into adjacent rooms are given "you can go: north..."

### ISSUE THREAD

**Issue by phillipgray** [code-newbies/python-thursday-adventure#13]

**Comment by rubyyot** [comment]
To discuss:  Is this necessary?

**Comment by jcode89** [comment]
Maybe in a later version? Right now it is open map like a chess board like @phillipgray was saying yesterday.

**Comment by rubyyot** [comment]
Right, the room is a square and you can move within it. I guess this one is to create non standard room shapes then?

**Comment by jcode89** [comment]
That was my thought, but it is kind of hard to create boards of different shapes.

**Comment by rubyyot** [comment]
Yeah I was thinking that maybe we could do something with drawing the map in the .json file with all the items. But that is something for later
