### ISSUE TITLE
Keep player from traveling outside of the room

### ISSUE THREAD

**Issue by rubyyot** [code-newbies/python-thursday-adventure#27]
Currently the room has a size, but the game allows you to travel outside it's walls.

**Comment by phillipgray** [comment]
@rubyyot @jcode89 this might be blasphemy, but what do you guys think about making every room the same size? like a chess board. this might simplify coding the position of each room as x and y coordinates.

**Comment by rubyyot** [comment]
@phillipgray We could do that, though it currently supports multiple sizes.  I'm not sure if making them all the same size will be an improvement, but I could be persuaded.

**Comment by jcode89** [comment]
I am okay with a standard room size.

**Comment by rubyyot** [comment]
edges of rooms are now impermeable
