### ISSUE TITLE
Player should be able to move around the map using arrow keys

### ISSUE THREAD

**Issue by jamalhansen** [code-newbies/python-thursday-adventure#39]
Player should be able to move around the map using arrow keys without having to press enter in between.

**Comment by rubyyot** [comment]
This may be the way forward here. https://docs.python.org/3.4/library/curses.html

**Comment by jcode89** [comment]
This looks extremely helpful, and definitely the way forward. 

Jonathan Colón

**Comment by kylegalloway** [comment]
https://gist.github.com/sanchitgangwar/2158089 (Dropping this for later reference.)

I'll take this.

**Comment by kylegalloway** [comment]
I'm closing this issue because it would take almost an entire rewrite to use curses and would also make it hard to on board new people. I plan to open a new issue to make it possible for the player to choose their own commands using a prompt.
