### ISSUE TITLE
Key and gold remain on the map after picking them up.

### ISSUE THREAD

**Issue by jamalhansen** [code-newbies/python-thursday-adventure#40]
Key and gold remain on the map after picking them up.  They should be removed from the room when they are placed in inventory.

**Comment by jcode89** [comment]
The pick_up_item method in the Room class should have a line of code that removes 'key' from the list that builds the map and do the same for 'gold' when that is found. It looks like the items method helps build the map, and the items method returns a list, so maybe have something removes items from that said list.

**Comment by jcode89** [comment]
Instead of removing an item from the found list returned by the items method, perhaps an if/elif/else statement can be added to the build map method that checks the bag for the key or gold and stops them from being printed on the map?

**Comment by rubyyot** [comment]
how would that work in other levels?

**Comment by jcode89** [comment]
Check to see what level you are on? ```if bag has gold and on level 1: take item off board.``` or go back to my original idea and once you pick up an item ```self.items().remove('gold')``` I am just sorting out ideas in my head right now, tomorrow or Sunday I will fool around with actual code.

**Comment by rubyyot** [comment]
cool
