### ISSUE TITLE
add enemy class

### ISSUE THREAD

**Issue by phillipgray** [code-newbies/python-thursday-adventure#48]

**Comment by jamalhansen** [comment]
Ok, not quite sure that this is, I will interpret it as create one enemy with a single default attack.

**Comment by phillipgray** [comment]
phillipg [9:32 PM] 
I wasn't sure what exactly to do with the enemy class. Running chain of ideas: have an enemy superclass with basic attributes and methods and subclasses as individual monsters, monsters are instantiated from the json file.

jvcode [9:32 PM] 
OH I like that idea

phillipg [9:32 PM] 
And that way there could be a custom set for each level.
And we could use rename actions.py and use it to house all this stuff.

jamal [9:37 PM] 
I am gonna make a single enemy first.  Then once we create a second enemy and/or combat we can figure out how to abstract

**Comment by jamalhansen** [comment]
I am gonna put this one back for now as I'm embroiled in an overhaul of the engine.

**Comment by jamalhansen** [comment]
If it is still around when I am done, I'll pick it back up.

**Comment by jamalhansen** [comment]
... and I'm back
