### ISSUE TITLE
game setup: add weapon class

### ISSUE THREAD

**Issue by phillipgray** [code-newbies/python-thursday-adventure#49]
add weapon class with name, description, and damage.

**Comment by jamalhansen** [comment]
I see tests, that's awesome!

**Comment by jcode89** [comment]
This is definitely an issue which would need to obey the testing goat.

**Comment by jamalhansen** [comment]
# Obey the testing goat
![goat_up_a_tree_flickr_caitlinstewart_2846642630_cropped](https://cloud.githubusercontent.com/assets/38428/8640750/5798e312-28c9-11e5-9585-f73501ca5571.jpg)

**Comment by jcode89** [comment]
YESSS!!!! @jamalhansen

**Comment by phillipgray** [comment]
Ha. Of course. Is there any other way?!
[applies testing goat temporary tattoo]

**Comment by jcode89** [comment]
That is how you know @phillipgray is committed! :+1: :)
