### ISSUE TITLE
Game setup: there is a start tile, where players start the game

### ISSUE THREAD

**Issue by phillipgray** [code-newbies/python-thursday-adventure#5]

**Comment by rubyyot** [comment]
This is generally completed, though it could be more solidified.   Currently the player begins the game with "begin" and they are inserted into level 1 at the "entrance" location.

**Comment by jcode89** [comment]
I would agree that since you type in "begin" and are inserted to the first level, that could be considered the 'start' tile.

**Comment by rubyyot** [comment]
Each room has an entry point.. This is complete, closing.
