### ISSUE TITLE
research/use __init__.py to do single load of necessary modules

### ISSUE THREAD

**Issue by phillipgray** [code-newbies/python-thursday-adventure#64]

**Comment by jcode89** [comment]
Okay so I found this reddit link for [__init__.py](http://www.reddit.com/r/Python/comments/1bbbwk/whats_your_opinion_on_what_to_include_in_init_py/). I found it quite interesting.

**Comment by jamalhansen** [comment]
Interesting.. Thanks @jcode89

**Comment by jcode89** [comment]
Not a problem @jamalhansen
