### ISSUE TITLE
General code review and clean up

### ISSUE THREAD

**Issue by jamalhansen** [code-newbies/python-thursday-adventure#67]
After adding the first monster there are probably going to be some maintenance items that need to be addressed.

**Comment by kylegalloway** [comment]
Should we merge Pull request https://github.com/code-newbies/python-thursday-adventure/issues/63 with this one? Or is this your own review/cleanup for the cockroach stuff?

**Comment by jamalhansen** [comment]
I can grab #63 too.  It makes sense to combine them

**Comment by kylegalloway** [comment]
Ok I'll close #63 and change the title for this issue.

**Comment by jamalhansen** [comment]
thanks!

**Comment by jamalhansen** [comment]
found pylint.  It is very strict, but good feedback.

**Comment by jcode89** [comment]
I have to check that out :)

**Comment by jamalhansen** [comment]
I've boosted the score from around 5 to almost 8 so far.  Pylint checks for PEP 8 standards as well as some other stuff.   Some it is is nit-picky but other stuff is good feedback.  I think you can configure it to ignore certain feedback.

https://github.com/code-newbies/python-thursday-adventure/blob/jh-deep-cleaning/pylint.output#L304

**Comment by jcode89** [comment]
It looks awesome, I love how it reports everything like that. I feel like that is handy for anyone who isn't really up with PEP 8

**Comment by jamalhansen** [comment]
agreed

**Comment by jamalhansen** [comment]
I think you are right @phillipgray .  This one can close
