### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by kylegalloway** [code-newbies/python-thursday-adventure#68]
The documentation for getting up and running with this project is lacking. The current README.md offers no information about the game's goal or current state.

Also, the code needs documenting.

**Comment by phillipgray** [comment]
This is now just to update the README.md

**Comment by kylegalloway** [comment]
Completed with this commit https://github.com/code-newbies/python-thursday-adventure/commit/201811726cc02ef682ff02a8745e542e76e707f1
