### ISSUE TITLE
Assigned movement commands might overwrite a pre-set command (in which case, neither will work).

### ISSUE THREAD

**Issue by kylegalloway** [code-newbies/python-thursday-adventure#78]
I can't seem to get the assigned westward movement working. It takes the command, but the map doesn't update.

**Comment by degustaf** [comment]
What key did you assign to westward movement?

**Comment by kylegalloway** [comment]
Ah, I see that it overwrites the return item count.... (I was using w,a,s,d as the movement)

**Comment by degustaf** [comment]
That's still an issue.  Just a different issue.

**Comment by kylegalloway** [comment]
Possible solutions:
1. Show commands that are already assigned first.
2. Allow all commands to be assigned. (I don't like this one.)
3. Change pre-set commands to be capital?

**Comment by kylegalloway** [comment]
Whoops
We changed the title at the same time

**Comment by phillipgray** [comment]
I was going to go with just protecting the existing commands; as in a
try/except block. with a warning to the user of taken keys.

**Comment by kylegalloway** [comment]
+1

**Comment by degustaf** [comment]
Does neither work?  I would expect one of them to work.

I would vote for option 1, combined with @phillipgray 's suggestion.

**Comment by kylegalloway** [comment]
I would also suggest changing the item count to c. Most people that are self assigning the keys, will use either wasd, ijkl, or hjkl.

Side note (possibly different issue that can't be solved without using ncurses): Assigning to the arrow keys does not work.
Solution: A warning of don't assign to arrow keys (and inclusion in the try/catch).

**Comment by kylegalloway** [comment]
@degustaf the item listing works as expected.
