### ISSUE TITLE
Game setup: make the end

### ISSUE THREAD

**Issue by phillipgray** [code-newbies/python-thursday-adventure#8]

**Comment by rubyyot** [comment]
I think that the way we can do this and maintain the configurable .json approach is to add a section to the .json room file called  items_required_to_exit and include key in the list.

**Comment by jcode89** [comment]
I think that works, have key in there and item in bag must == key to exit?

**Comment by rubyyot** [comment]
yeah something like that

it not 'key' in bag:
    print("hold on there")

**Comment by rubyyot** [comment]
will need to work through picking up items and displaying inventory first

**Comment by jcode89** [comment]
Yeah that could get a little more crazy.

**Comment by phillipgray** [comment]
I could tackle this one. I'm taking a look at the items module. It would be pretty easy to add a new key class, and then check to see if the bag contains it.

**Comment by phillipgray** [comment]
This might also be a good time/issue to add descriptions(as a class attribute) to the objects, and be able to hit a key command to see an object's description.

**Comment by rubyyot** [comment]
Sounds good!  go for it

**Comment by kylegalloway** [comment]
Whoops
